jobs:
  include:
  - stage: deploy 2
    language: php
    php:
    - 7.1
    cache:
      directories:
      - "$HOME/.composer/cache"
    before_install:
    - cd Slim
    - travis_retry composer self-update
    - openssl aes-256-cbc -K $encrypted_0b41b2239e5d_key -iv $encrypted_0b41b2239e5d_iv
-in deploy_key.enc -out ./Slim/deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host 108.167.188.84\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    install:
    - travis_retry composer install --no-interaction --prefer-source
    deploy:
      provider: script
      skip_cleanup: true
      script: rsync -r -e  'ssh -i ./deploy_key -p 2222' --quiet --delete-after ./*
        jrpiresc@108.167.188.84:~/public_html/rest
      on:
        branch: master

